"""WRAITH Cell v5.0 — Threat Intelligence Feed Agent.
Pulls live threat data from multiple sources and creates local defense rules.
Covers: AI attacks, CVEs, ransomware, APT groups, zero-days, MCP vulnerabilities.
"""
from __future__ import annotations
import logging, time, json, hashlib, threading, sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

_LOG = logging.getLogger("wraith.threat_feed")

CELL_HOME = Path.home() / ".wraith"
THREAT_DB = CELL_HOME / "threat_intel.db"

# Threat intelligence sources (free, no API key needed)
THREAT_SOURCES = {
    "cve_recent": "https://cve.circl.lu/api/last/20",
    "ransomware_tracker": "https://api.ransomware.live/v2/recent",
    "urlhaus": "https://urlhaus-api.abuse.ch/v1/urls/recent/20",
    "alienvault_otx": "https://otx.alienvault.com/api/v1/indicators/IPv4/general",
}

# Known AI-powered threat actors and their TTPs
AI_THREAT_ACTORS = {
    "APT42": {
        "origin": "Iran",
        "targets": ["defense", "government", "tech"],
        "ai_usage": ["automated recon", "target profiling", "spear-phishing"],
        "tools": ["Gemini", "custom LLMs"],
    },
    "Lazarus": {
        "origin": "North Korea",
        "targets": ["crypto", "defense", "finance"],
        "ai_usage": ["automated scanning", "exploit generation", "social engineering"],
        "tools": ["custom AI", "LLM-assisted malware"],
    },
    "Salt Typhoon": {
        "origin": "China",
        "targets": ["telecom", "government", "critical infrastructure"],
        "ai_usage": ["automated exploitation", "lateral movement"],
        "tools": ["AI-assisted tooling"],
    },
    "Volt Typhoon": {
        "origin": "China",
        "targets": ["critical infrastructure", "energy", "water"],
        "ai_usage": ["pre-positioning", "automated persistence"],
        "tools": ["living-off-land AI"],
    },
    "Scattered Spider": {
        "origin": "Russia",
        "targets": ["tech", "telecom", "MSSPs"],
        "ai_usage": ["deepfake voice", "automated social engineering"],
        "tools": ["AI voice clone", "LLM-generated phishing"],
    },
    "MFA Spoofing Groups": {
        "origin": "Various",
        "targets": ["enterprise", "cloud"],
        "ai_usage": ["MFA bypass automation", "session hijacking"],
        "tools": ["EvilProxy", "AI-generated lures"],
    },
}

# Current AI-specific attack vectors (2026)
AI_ATTACK_VECTORS = [
    {
        "id": "AI-001",
        "name": "Prompt Injection",
        "description": "Attackers inject malicious instructions into LLM prompts",
        "severity": "critical",
        "mitigation": "Input validation, prompt sandboxing, output filtering",
    },
    {
        "id": "AI-002",
        "name": "MCP Tool Injection",
        "description": "Malicious tool calls via Model Context Protocol",
        "severity": "critical",
        "mitigation": "Tool call validation, permission scoping, audit logging",
    },
    {
        "id": "AI-003",
        "name": "AI Agent Hijacking",
        "description": "Taking control of autonomous AI agents via crafted inputs",
        "severity": "critical",
        "mitigation": "Agent sandboxing, action approval, scope limitation",
    },
    {
        "id": "AI-004",
        "name": "Deepfake Voice Phishing",
        "description": "AI-generated voice calls impersonating executives",
        "severity": "high",
        "mitigation": "Voice verification, callback procedures, employee training",
    },
    {
        "id": "AI-005",
        "name": "LLM Data Exfiltration",
        "description": "Extracting training data or sensitive info from LLMs",
        "severity": "high",
        "mitigation": "Output filtering, rate limiting, data classification",
    },
    {
        "id": "AI-006",
        "name": "Autonomous Malware",
        "description": "AI-powered malware that adapts and evolves in real-time",
        "severity": "critical",
        "mitigation": "Behavioral detection, AI-powered defense, network segmentation",
    },
    {
        "id": "AI-007",
        "name": "AI-Generated Phishing",
        "description": "Highly convincing phishing emails generated by LLMs",
        "severity": "high",
        "mitigation": "AI-aware email filtering, DMARC, employee awareness",
    },
    {
        "id": "AI-008",
        "name": "Model Poisoning",
        "description": "Corrupting ML training data to create backdoors",
        "severity": "high",
        "mitigation": "Data validation, model integrity checks, adversarial training",
    },
    {
        "id": "AI-009",
        "name": "Supply Chain AI Attack",
        "description": "Compromising AI/ML libraries and dependencies",
        "severity": "critical",
        "mitigation": "SBOM scanning, dependency pinning, code signing",
    },
    {
        "id": "AI-010",
        "name": "Agentic AI Espionage",
        "description": "AI agents autonomously conducting multi-step cyber espionage",
        "severity": "critical",
        "mitigation": "Zero-trust, behavioral monitoring, kill switch",
    },
]


class ThreatIntelligenceFeed:
    """
    Pulls threat intelligence from multiple sources.
    Creates local defense rules that the cell can install.
    """

    def __init__(self, config: dict) -> None:
        self.config = config
        self.active = False
        self._findings: list[dict] = []
        self._defense_rules: list[dict] = []
        self._last_fetch = 0.0
        self._db_path = str(THREAT_DB)
        self._init_db()
        _LOG.info("ThreatIntelligenceFeed initialized.")

    def _init_db(self):
        conn = sqlite3.connect(self._db_path)
        c = conn.cursor()
        c.executescript("""
            CREATE TABLE IF NOT EXISTS threat_intel (
                id TEXT PRIMARY KEY,
                source TEXT NOT NULL,
                threat_type TEXT NOT NULL,
                severity TEXT NOT NULL,
                indicator TEXT,
                description TEXT,
                mitre_technique TEXT,
                created_at TEXT NOT NULL,
                installed INTEGER DEFAULT 0
            );
            CREATE TABLE IF NOT EXISTS defense_rules (
                id TEXT PRIMARY KEY,
                threat_id TEXT NOT NULL,
                rule_type TEXT NOT NULL,
                rule_json TEXT NOT NULL,
                created_at TEXT NOT NULL,
                active INTEGER DEFAULT 1
            );
            CREATE INDEX IF NOT EXISTS idx_threat_severity ON threat_intel(severity);
            CREATE INDEX IF NOT EXISTS idx_threat_type ON threat_intel(threat_type);
        """)
        conn.commit()
        conn.close()

    def start(self) -> None:
        self.active = True
        # Seed with known AI attack vectors
        self._seed_ai_vectors()
        _LOG.info("ThreatIntelligenceFeed started.")

    def stop(self) -> None:
        self.active = False
        _LOG.info("ThreatIntelligenceFeed stopped.")

    def scan(self) -> dict[str, Any]:
        """Fetch latest threat intelligence and return findings."""
        try:
            findings = []
            now = time.time()

            # 1. Fetch CVEs
            cves = self._fetch_cves()
            findings.extend(cves)

            # 2. Check AI attack vectors
            ai_threats = self._check_ai_vectors()
            findings.extend(ai_threats)

            # 3. Check known threat actors
            actor_intel = self._check_threat_actors()
            findings.extend(actor_intel)

            # 4. Generate defense rules from findings
            for f in findings:
                rule = self._generate_defense_rule(f)
                if rule:
                    self._defense_rules.append(rule)

            self._findings.extend(findings)
            self._last_fetch = now

            return {
                "status": "ok",
                "new_threats": len(findings),
                "total_threats": len(self._findings),
                "defense_rules": len(self._defense_rules),
                "findings": findings[:10],  # Return top 10
            }
        except Exception as exc:
            _LOG.error("Threat intel scan failed: %s", exc)
            return {"status": "error", "error": str(exc)}

    def analyze(self, data: dict[str, Any]) -> dict[str, Any]:
        """Analyze threat intelligence findings."""
        try:
            findings = data.get("findings", [])
            if not findings:
                return {"threat_level": "low", "score": 0}

            severity_scores = {"critical": 40, "high": 25, "medium": 10, "low": 5}
            total = sum(severity_scores.get(f.get("severity", "low"), 5) for f in findings)
            score = min(total, 100)

            level = "low"
            if score >= 75:
                level = "critical"
            elif score >= 50:
                level = "high"
            elif score >= 25:
                level = "medium"

            # Group by type
            by_type = {}
            for f in findings:
                t = f.get("threat_type", "unknown")
                by_type[t] = by_type.get(t, 0) + 1

            return {
                "threat_level": level,
                "score": score,
                "by_type": by_type,
                "top_threats": [f.get("name", f.get("indicator", "unknown")) for f in findings[:5]],
            }
        except Exception as exc:
            return {"status": "error", "error": str(exc)}

    def report(self) -> dict[str, Any]:
        return {
            "agent": "ThreatIntelligenceFeed",
            "active": self.active,
            "total_threats": len(self._findings),
            "defense_rules": len(self._defense_rules),
            "last_fetch": self._last_fetch,
        }

    def get_active_rules(self) -> List[Dict]:
        """Return all active defense rules."""
        return [r for r in self._defense_rules if r.get("active", True)]

    def _seed_ai_vectors(self):
        """Seed the database with known AI attack vectors."""
        conn = sqlite3.connect(self._db_path)
        c = conn.cursor()
        now = datetime.now().isoformat()
        for vec in AI_ATTACK_VECTORS:
            try:
                c.execute(
                    "INSERT OR IGNORE INTO threat_intel (id, source, threat_type, severity, description, created_at) VALUES (?,?,?,?,?,?)",
                    (vec["id"], "wraith-ai-vectors", "ai_attack", vec["severity"], vec["description"], now),
                )
            except Exception:
                pass
        conn.commit()
        conn.close()

    def _fetch_cves(self) -> list[dict]:
        """Fetch recent CVEs from CIRCL API."""
        findings = []
        try:
            import urllib.request
            req = urllib.request.Request(THREAT_SOURCES["cve_recent"])
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read())
            for item in data[:10]:
                cve_id = item.get("id", "")
                summary = item.get("summary", "")
                severity = self._cvss_to_severity(item.get("cvss", 5.0))
                findings.append({
                    "name": cve_id,
                    "threat_type": "cve",
                    "severity": severity,
                    "indicator": cve_id,
                    "description": summary[:200],
                    "mitre_technique": item.get("capec", ""),
                    "source": "circl-cve",
                    "ts": time.time(),
                })
                # Store in DB
                self._store_threat(cve_id, "circl-cve", "cve", severity, cve_id, summary[:200])
        except Exception as exc:
            _LOG.debug("CVE fetch failed: %s", exc)
        return findings

    def _check_ai_vectors(self) -> list[dict]:
        """Check for active AI attack vectors."""
        findings = []
        conn = sqlite3.connect(self._db_path)
        c = conn.cursor()
        rows = c.execute(
            "SELECT * FROM threat_intel WHERE threat_type='ai_attack' AND severity IN ('critical','high')"
        ).fetchall()
        for row in rows:
            findings.append({
                "name": row[4] or row[0],
                "threat_type": "ai_attack",
                "severity": row[3],
                "indicator": row[4],
                "description": row[5],
                "source": row[1],
                "ts": time.time(),
            })
        conn.close()
        return findings

    def _check_threat_actors(self) -> list[dict]:
        """Generate intel on known AI-using threat actors."""
        findings = []
        for name, info in AI_THREAT_ACTORS.items():
            findings.append({
                "name": f"Threat Actor: {name}",
                "threat_type": "apt",
                "severity": "high",
                "indicator": name,
                "description": f"{info['origin']}-backed group using AI for {', '.join(info['ai_usage'])}",
                "source": "wraith-intel",
                "ts": time.time(),
            })
        return findings

    def _generate_defense_rule(self, finding: dict) -> Optional[dict]:
        """Generate a defense rule from a threat finding."""
        threat_type = finding.get("threat_type", "")
        severity = finding.get("severity", "low")

        rule = {
            "id": hashlib.sha256(f"{finding.get('name', '')}:{time.time()}".encode()).hexdigest()[:16],
            "threat_id": finding.get("indicator", ""),
            "rule_type": threat_type,
            "severity": severity,
            "action": "alert" if severity in ("medium", "low") else "block",
            "created_at": datetime.now().isoformat(),
            "active": True,
        }

        # Store in DB
        try:
            conn = sqlite3.connect(self._db_path)
            c = conn.cursor()
            c.execute(
                "INSERT OR IGNORE INTO defense_rules (id, threat_id, rule_type, rule_json, created_at) VALUES (?,?,?,?,?)",
                (rule["id"], rule["threat_id"], rule["rule_type"], json.dumps(rule), rule["created_at"]),
            )
            conn.commit()
            conn.close()
        except Exception:
            pass

        return rule

    def _store_threat(self, id, source, threat_type, severity, indicator, description):
        try:
            conn = sqlite3.connect(self._db_path)
            c = conn.cursor()
            c.execute(
                "INSERT OR IGNORE INTO threat_intel (id, source, threat_type, severity, indicator, description, created_at) VALUES (?,?,?,?,?,?,?)",
                (id, source, threat_type, severity, indicator, description, datetime.now().isoformat()),
            )
            conn.commit()
            conn.close()
        except Exception:
            pass

    @staticmethod
    def _cvss_to_severity(cvss: float) -> str:
        if cvss >= 9.0:
            return "critical"
        if cvss >= 7.0:
            return "high"
        if cvss >= 4.0:
            return "medium"
        return "low"
